[2024-05-22T15:37:13.899+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-22T15:37:13.912+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: disney_api.get_data manual__2024-05-22T15:37:12.553988+00:00 [queued]>
[2024-05-22T15:37:13.919+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: disney_api.get_data manual__2024-05-22T15:37:12.553988+00:00 [queued]>
[2024-05-22T15:37:13.920+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-05-22T15:37:13.930+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_data> on 2024-05-22 15:37:12.553988+00:00
[2024-05-22T15:37:13.936+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'disney_api', 'get_data', 'manual__2024-05-22T15:37:12.553988+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/disney_api_dag.py', '--cfg-path', '/tmp/tmpvr91m_m_']
[2024-05-22T15:37:13.940+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask get_data
[2024-05-22T15:37:13.940+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=642) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-22T15:37:13.941+0000] {standard_task_runner.py:63} INFO - Started process 644 to run task
[2024-05-22T15:37:13.981+0000] {task_command.py:426} INFO - Running <TaskInstance: disney_api.get_data manual__2024-05-22T15:37:12.553988+00:00 [running]> on host b4db1197dafa
[2024-05-22T15:37:14.047+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='marcelo.vicente@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='disney_api' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-22T15:37:12.553988+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-22T15:37:12.553988+00:00'
[2024-05-22T15:37:14.049+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-22T15:37:14.058+0000] {logging_mixin.py:188} INFO - https://api.disneyapi.dev/character
[2024-05-22T15:37:14.842+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-22T15:37:14.843+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/disney_api_dag.py", line 31, in get_data
    df = pd.DataFrame(json.loads(response.text))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 733, in __init__
    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/internals/construction.py", line 503, in dict_to_mgr
    return arrays_to_mgr(arrays, columns, index, dtype=dtype, typ=typ, consolidate=copy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/internals/construction.py", line 114, in arrays_to_mgr
    index = _extract_index(arrays)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/internals/construction.py", line 680, in _extract_index
    raise ValueError(
ValueError: Mixing dicts with non-Series may lead to ambiguous ordering.
[2024-05-22T15:37:14.857+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=disney_api, task_id=get_data, run_id=manual__2024-05-22T15:37:12.553988+00:00, execution_date=20240522T153712, start_date=20240522T153713, end_date=20240522T153714
[2024-05-22T15:37:14.868+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 7 for task get_data (Mixing dicts with non-Series may lead to ambiguous ordering.; 644)
[2024-05-22T15:37:14.880+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-22T15:37:14.897+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-22T15:37:14.901+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
