[2024-05-22T22:07:09.919+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-22T22:07:09.934+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: disney_api.saving_raw_data manual__2024-05-22T22:07:05.725161+00:00 [queued]>
[2024-05-22T22:07:09.942+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: disney_api.saving_raw_data manual__2024-05-22T22:07:05.725161+00:00 [queued]>
[2024-05-22T22:07:09.944+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-22T22:07:09.955+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): saving_raw_data> on 2024-05-22 22:07:05.725161+00:00
[2024-05-22T22:07:09.961+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'disney_api', 'saving_raw_data', 'manual__2024-05-22T22:07:05.725161+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/disney_api_dag.py', '--cfg-path', '/tmp/tmptjrpyq8w']
[2024-05-22T22:07:09.964+0000] {standard_task_runner.py:91} INFO - Job 65: Subtask saving_raw_data
[2024-05-22T22:07:09.965+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1169) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-22T22:07:09.965+0000] {standard_task_runner.py:63} INFO - Started process 1171 to run task
[2024-05-22T22:07:10.002+0000] {task_command.py:426} INFO - Running <TaskInstance: disney_api.saving_raw_data manual__2024-05-22T22:07:05.725161+00:00 [running]> on host 4f9488b8581a
[2024-05-22T22:07:10.074+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='marcelo.vicente@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='disney_api' AIRFLOW_CTX_TASK_ID='saving_raw_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-22T22:07:05.725161+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-22T22:07:05.725161+00:00'
[2024-05-22T22:07:10.075+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-22T22:07:10.128+0000] {logging_mixin.py:188} INFO - <class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   _id              50 non-null     int64 
 1   films            50 non-null     object
 2   shortFilms       50 non-null     object
 3   tvShows          50 non-null     object
 4   videoGames       50 non-null     object
 5   parkAttractions  50 non-null     object
 6   allies           50 non-null     object
 7   enemies          50 non-null     object
 8   sourceUrl        50 non-null     object
 9   name             50 non-null     object
 10  imageUrl         48 non-null     object
 11  createdAt        50 non-null     object
 12  updatedAt        50 non-null     object
 13  url              50 non-null     object
 14  __v              50 non-null     int64 
dtypes: int64(2), object(13)
memory usage: 6.0+ KB
[2024-05-22T22:07:10.129+0000] {logging_mixin.py:188} INFO - 50
[2024-05-22T22:07:10.139+0000] {base.py:84} INFO - Using connection ID 'aws_default' for task execution.
[2024-05-22T22:07:10.140+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2024-05-22T22:07:12.473+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-22T22:07:12.474+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/disney_api_dag.py", line 56, in saving_raw_data
    df_01 = pd.read_parquet(s3_raw_path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 670, in read_parquet
    return impl.read(
           ^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 272, in read
    pa_table = self.api.parquet.read_table(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyarrow/parquet/core.py", line 1762, in read_table
    dataset = ParquetDataset(
              ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyarrow/parquet/core.py", line 1315, in __init__
    finfo = filesystem.get_file_info(path_or_paths)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow/_fs.pyx", line 584, in pyarrow._fs.FileSystem.get_file_info
  File "pyarrow/error.pxi", line 154, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 91, in pyarrow.lib.check_status
OSError: When getting information for key 'input/disney/character/*.parquet' in bucket 'mvs-sync': AWS Error ACCESS_DENIED during HeadObject operation: No response body.
[2024-05-22T22:07:12.483+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=disney_api, task_id=saving_raw_data, run_id=manual__2024-05-22T22:07:05.725161+00:00, execution_date=20240522T220705, start_date=20240522T220709, end_date=20240522T220712
[2024-05-22T22:07:12.494+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 65 for task saving_raw_data (When getting information for key 'input/disney/character/*.parquet' in bucket 'mvs-sync': AWS Error ACCESS_DENIED during HeadObject operation: No response body.; 1171)
[2024-05-22T22:07:12.516+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-22T22:07:12.529+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-22T22:07:12.532+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
