[2024-05-22T16:27:14.983+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-22T16:27:14.996+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: disney_api.has_data manual__2024-05-22T16:27:10.595844+00:00 [queued]>
[2024-05-22T16:27:15.003+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: disney_api.has_data manual__2024-05-22T16:27:10.595844+00:00 [queued]>
[2024-05-22T16:27:15.005+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-22T16:27:15.016+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): has_data> on 2024-05-22 16:27:10.595844+00:00
[2024-05-22T16:27:15.023+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'disney_api', 'has_data', 'manual__2024-05-22T16:27:10.595844+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/disney_api_dag.py', '--cfg-path', '/tmp/tmpc_h4n_bu']
[2024-05-22T16:27:15.025+0000] {standard_task_runner.py:91} INFO - Job 10: Subtask has_data
[2024-05-22T16:27:15.025+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1862) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-22T16:27:15.026+0000] {standard_task_runner.py:63} INFO - Started process 1864 to run task
[2024-05-22T16:27:15.064+0000] {task_command.py:426} INFO - Running <TaskInstance: disney_api.has_data manual__2024-05-22T16:27:10.595844+00:00 [running]> on host b4db1197dafa
[2024-05-22T16:27:15.129+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='marcelo.vicente@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='disney_api' AIRFLOW_CTX_TASK_ID='has_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-22T16:27:10.595844+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-22T16:27:10.595844+00:00'
[2024-05-22T16:27:15.131+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-22T16:27:15.140+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-05-22T16:27:15.141+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-22T16:27:15.142+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 269, in execute
    return self.do_branch(context, super().execute(context))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/disney_api_dag.py", line 60, in has_data
    return 'processing_data' if ( len(df.index) > 0 ) else 'alarm_dag'
                                  ^^^^^^^^^^^^^
TypeError: object of type 'method' has no len()
[2024-05-22T16:27:15.157+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=disney_api, task_id=has_data, run_id=manual__2024-05-22T16:27:10.595844+00:00, execution_date=20240522T162710, start_date=20240522T162714, end_date=20240522T162715
[2024-05-22T16:27:15.166+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 10 for task has_data (object of type 'method' has no len(); 1864)
[2024-05-22T16:27:15.201+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-22T16:27:15.226+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-22T16:27:15.231+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
